services:
  - type: web
    name: univerbot-embedding
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    initialDelaySeconds: 30
    envVars:
      - key: PORT
        value: 8001
      - key: PYTHONUNBUFFERED
        value: 1
